<?php

namespace ContainerDvU4E7o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_UxIcons_TwigIconRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.ux_icons.twig_icon_runtime' shared service.
     *
     * @return \Symfony\UX\Icons\Twig\UXIconRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-icons/src/Twig/UXIconRuntime.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-icons/src/IconRendererInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-icons/src/IconRenderer.php';

        return $container->privates['.ux_icons.twig_icon_runtime'] = new \Symfony\UX\Icons\Twig\UXIconRuntime(new \Symfony\UX\Icons\IconRenderer(($container->privates['.ux_icons.cache_icon_registry'] ?? $container->load('get_UxIcons_CacheIconRegistryService')), ['width' => '1.2em', 'height' => '1.2em', 'style' => 'position: relative; top: -2px;'], ['tabler:save-changes' => 'tabler:device-floppy'], []), false, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
