<?php

namespace ContainerDvU4E7o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllercommentNewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jFa5KmS.App\Controller\BlogController::commentNew()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jFa5KmS.App\\Controller\\BlogController::commentNew()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', 'App\\Entity\\User', 'getUserService', true],
            'post' => ['privates', 'App\\Entity\\Post', 'getPostService', true],
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'user' => 'App\\Entity\\User',
            'post' => 'App\\Entity\\Post',
            'eventDispatcher' => '?',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\BlogController::commentNew()', $container);
    }
}
