<?php

namespace ContainerDvU4E7o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AcfYa9Y.App\Controller\Admin\BlogController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AcfYa9Y.App\\Controller\\Admin\\BlogController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', 'App\\Entity\\User', 'getUserService', true],
            'posts' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'posts' => 'App\\Repository\\PostRepository',
        ]))->withContext('App\\Controller\\Admin\\BlogController::index()', $container);
    }
}
