<?php

namespace ContainerDvU4E7o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListUsersCommand_Command_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ListUsersCommand.command.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ListUsersCommand.command.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:list-users', ['app:users'], 'Lists all the existing users', false, #[\Closure(name: 'App\\Command\\ListUsersCommand.command', class: 'Symfony\\Component\\Console\\Command\\Command')] fn (): \Symfony\Component\Console\Command\Command => ($container->privates['App\\Command\\ListUsersCommand.command'] ?? $container->load('getListUsersCommand_CommandService')));
    }
}
