<?php

namespace ContainerDvU4E7o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeInfo_Resolver_ReflectionPropertyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'type_info.resolver.reflection_property' shared service.
     *
     * @return \Symfony\Component\TypeInfo\TypeResolver\ReflectionPropertyTypeResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/type-info/TypeResolver/ReflectionPropertyTypeResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/type-info/TypeContext/TypeContextFactory.php';

        return $container->privates['type_info.resolver.reflection_property'] = new \Symfony\Component\TypeInfo\TypeResolver\ReflectionPropertyTypeResolver(($container->privates['type_info.resolver.reflection_type'] ?? $container->load('getTypeInfo_Resolver_ReflectionTypeService')), ($container->privates['type_info.type_context_factory'] ??= new \Symfony\Component\TypeInfo\TypeContext\TypeContextFactory(NULL)));
    }
}
