<?php

namespace ContainerDvU4E7o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_QueryStringInitializerSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.live_component.query_string_initializer_subscriber' shared service.
     *
     * @return \Symfony\UX\LiveComponent\EventListener\RequestInitializeSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/EventListener/RequestInitializeSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/Util/RequestPropsExtractor.php';

        $a = ($container->privates['ux.live_component.component_hydrator'] ?? $container->load('getUx_LiveComponent_ComponentHydratorService'));

        if (isset($container->privates['ux.live_component.query_string_initializer_subscriber'])) {
            return $container->privates['ux.live_component.query_string_initializer_subscriber'];
        }

        return $container->privates['ux.live_component.query_string_initializer_subscriber'] = new \Symfony\UX\LiveComponent\EventListener\RequestInitializeSubscriber(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['ux.live_component.metadata_factory'] ?? self::getUx_LiveComponent_MetadataFactoryService($container)), new \Symfony\UX\LiveComponent\Util\RequestPropsExtractor($a), ($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)));
    }
}
