<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDvU4E7o\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDvU4E7o/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDvU4E7o.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDvU4E7o\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDvU4E7o\App_KernelDevDebugContainer([
    'container.build_hash' => 'DvU4E7o',
    'container.build_id' => 'f207f969',
    'container.build_time' => 1764261108,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDvU4E7o');
